### ISSUE TITLE
Farm.

### ISSUE THREAD

**Issue by Zaninbm** [stefan2200/TWB#15]
Hi, great bot, but farm isn't work... Maybe only if I had send farm manually, but it keeps sending 20 spears alone to the vill in reportd, even if lost one or two in process because lucky it send again same num.

**Comment by stefan2200** [comment]
Hi, the bot does not automatically attack barbarian villages because they might contain troops. That is why the manual attack did start the farming run. You can go to the cache folder, loop up the village ID (should be in your address bar when clicking on the village) and set "safe" to True. Additionally, you can set `"force_scout_if_available": true` to `"force_scout_if_available": false` in the config.json file but it is not recommended. By default the bot will only manually re-farm villages until scouts are researched / created. Then it will scout the village and only farm if troops are 0 and wall is 0.

Also if you want to send different farm units you can change the `"farm"` section in the `templates/troops` folder.

**Comment by Zaninbm** [comment]
Nice explanation, very intuitive, I can understand it now, thank u.
