### ISSUE TITLE
Cannot do more

### ISSUE THREAD

**Issue by siveti** [stefan2200/TWB#24]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\sivet\OneDrive\Pulpit\TWB-master> python twb.py
2022-03-11 15:59:13 - Requests - DEBUG - GET https://pl175.plemiona.pl/game.php?screen=overview [200]
2022-03-11 15:59:13 - Requests - DEBUG - Set CSRF token
2022-03-11 15:59:13 - Requests - WARNING - Current session cache not valid
Enter browser cookie string> https://pl175.plemiona.pl/game.php?village=17376&screen=overview
2022-03-11 15:59:52 - Requests - INFO - Game Endpoint: https://pl175.plemiona.pl/game.php
2022-03-11 16:00:00 - Requests - DEBUG - GET https://pl175.plemiona.pl/game.php?screen=overview_villages [200]
2022-03-11 16:00:00 - Requests - DEBUG - Set CSRF token
2022-03-11 16:00:00 - FarmManager - INFO - Villages: 0 
2022-03-11 16:00:00 - FarmManager - INFO - Reports: 0
2022-03-11 16:00:00 - FarmManager - INFO - Farms: 0
2022-03-11 16:00:00 - FarmManager - INFO - Total loot: {'wood': 0, 'iron': 0, 'stone': 0}
Dead for 3.666667.2 minutes (next run at: 16:03:40.255302)
2022-03-11 16:03:44 - Requests - DEBUG - GET https://pl175.plemiona.pl/game.php?screen=overview_villages [200]
2022-03-11 16:03:44 - Requests - DEBUG - Set CSRF token
2022-03-11 16:03:44 - FarmManager - INFO - Villages: 0
2022-03-11 16:03:44 - FarmManager - INFO - Reports: 0
2022-03-11 16:03:44 - FarmManager - INFO - Farms: 0
2022-03-11 16:03:44 - FarmManager - INFO - Total loot: {'wood': 0, 'iron': 0, 'stone': 0}
Dead for 4.683333.2 minutes (next run at: 16:08:25.898313)
2022-03-11 16:08:31 - Requests - DEBUG - GET https://pl175.plemiona.pl/game.php?screen=overview_villages [200]
2022-03-11 16:08:31 - Requests - DEBUG - Set CSRF token
2022-03-11 16:08:31 - FarmManager - INFO - Villages: 0
2022-03-11 16:08:31 - FarmManager - INFO - Reports: 0
2022-03-11 16:08:31 - FarmManager - INFO - Farms: 0
2022-03-11 16:08:31 - FarmManager - INFO - Total loot: {'wood': 0, 'iron': 0, 'stone': 0}
Dead for 4.500000.2 minutes (next run at: 16:13:01.560954)

**Comment by stefan2200** [comment]
You have to set the cookie string used by your browser.
[https://developer.chrome.com/docs/devtools/network/](url)

**Comment by delyro** [comment]
I have occured the same thing before, seems like you have to stop script and run again to make it work.

**Comment by siveti** [comment]
I did restart it a couple times
your link doesnt seems to work
u mean cookie string like this?
 https://pl175.plemiona.pl/game.php?village="5numbers"&screen=overview

**Comment by siveti** [comment]
Also i would like to see the Scavenging option, looks like easy on programing, its only need to select % of troops for each options 1 2 3 or 4th then just press one button

**Comment by siveti** [comment]
or this long one starting with cid="

**Comment by siveti** [comment]
okay, i just messed up, but fixed it, soo lets get back to scavenging option, is planned to add?

**Comment by siveti** [comment]
kekw its "gather_enabled" but how i can change it to not use lights

**Comment by stefan2200** [comment]
Hi, nice that you figured it out. `cid` was indeed the cookie line. Scavenging is working but the stuff you see in your browser is all done client-side so pretty hard to implement across multiple TW sites.
To disable light you can replace line 379 in `game/troopmanager.py` with `if item in troops and int(troops[item]) > 0 and item != "light":` and restart the bot.

**Comment by ovy17** [comment]
can you provide a ready to start example config file?
with villages etc. 

at my place the bot loads villages but does not build anything from the template.

**Comment by siveti** [comment]
nearly everything works just fine im happy with this but if u could help me with these things that just wont work for me:
1. When im not at home for some hours bot just stop at capcha is there any way to get thru with capcha in next patches?
2. How do i run "configuration dashboard" its like gui helper app?
3. Trade for premium function is selling? Like account on premium world ll grather some PP's
4.  Running manager.py with "Process finished with exit code 0" and nothing more
5. When i select priority for snob, bot stops recruting troops when i would like to have 24/7 recruit que , but it ll build like nothing changed. In my opinion priority for snob should work like 1h baracks, stable, workshop que and one building or two. Not like now when i got 3 buildings in que and 0 troops.
6. Can u plan a snipe defence in between one of 4 snobs?
7. How does "support_others" works in depth? 
I know this small q&a may look silly but im not into programing that much

**Comment by stefan2200** [comment]
A bit late since I've been working on a lot of other projects but:
**When im not at home for some hours bot just stop at capcha is there any way to get thru with capcha in next patches?**
Nope, there currently is no proper way to crack recaptcha, that is why using the browser session regularly is recommended.

**How do i run "configuration dashboard" its like gui helper app?**
Open a second terminal in the TWB directory and run `cd webmanager; python server.py`. If it starts then it should show the URL to open the web GUI.

**Trade for premium function is selling? Like account on premium world ll grather some PP's**
Trade for premium is selling left-over resources for premium points (if the world allows it).

**Running manager.py with "Process finished with exit code 0" and nothing more**
The farm manager is integrated into the bot and automatically optimizes the farms and the end of every run. No need to run it yourself.

**When i select priority for snob, bot stops recruting troops when i would like to have 24/7 recruit que , but it ll build like nothing changed. In my opinion priority for snob should work like 1h baracks, stable, workshop que and one building or two. Not like now when i got 3 buildings in que and 0 troops.***
Not sure about this one. I think it queues the priority like snob->building->troops. If there is not enough resources for a snob then why prioritize it? :)

**Can u plan a snipe defence in between one of 4 snobs?**
Well, the code is there [https://github.com/stefan2200/TWB/blob/master/game/hunter.py](https://github.com/stefan2200/TWB/blob/master/game/hunter.py) there is just way too much variables to implement it TW wide.

**How does "support_others" works in depth?**
You can enable this on defensive villages and it will automatically support villages which are under attack with x amount of the defensive units available.

I hope this helps you out a little :)
