### ISSUE TITLE
help me villages 0

### ISSUE THREAD

**Issue by Ashemaniko** [stefan2200/TWB#43]
villages 0 
wood 0 iron 0 

Why is this happening ?

**Comment by Ashemaniko** [comment]
![Ekran görüntüsü 2023-04-02 233155 - Kopya](https://user-images.githubusercontent.com/124808963/229377646-2e82489c-973e-4cc0-809d-3f1d659970d8.png)

**Comment by stefan2200** [comment]
Hi @Ashemaniko, I'm not sure what is happening but it looks like an issue I've experienced in the past. You can probably fix it by pressing CRTL+C and restarting the bot two or three times. Btw I've removed the picture because it contained your session identifiers, not the smartest idea to put those online :)

**Comment by jedmangubat** [comment]
i have this issue. i restarted many times already but still won't add villages to the config file

**Comment by stefan2200** [comment]
Bug was fixed in #53
