### ISSUE TITLE
prioritizing certain village to farm?| attacking players villages

### ISSUE THREAD

**Issue by mido4040e** [stefan2200/TWB#44]
Hi stefan, thanks for your great bot 
how can i prioritze certain villages to farm? i tried to put the villages id in "additional_farms": ["667","986"] like that but the bot didn't really start to attack them
and if i magaged to use the additional farms method will  it work on players villages id?
is there a method to make the bot save resources for unit upgrade instade of a building?

**Comment by stefan2200** [comment]
Hi, glad you like it so far!
The `additional_farms` list only defines a list of player-owned villages that the bot can attack. If the farming does not start you might need to find the village cache file in the villages directory (should be the village ID) and set both `safe` and `scout` to `true`. For the upgrade prioritization I think this needs some modifications to the code. You might be able to copy some stuff from the other prioritization functions, didn't implement it at the time because it was not really useful on the worlds I played on.
