### ISSUE TITLE
Forced peace time question

### ISSUE THREAD

**Issue by MariusDac** [stefan2200/TWB#64]
Great job with the script,works well.
2 issues that i have :)
What is the correct format for peace time?Anything ive tried ends in breaking the code
"forced_peace_times": []
My other issue is the web interface,always shows always inactive,even when bot is running,but i can leave with that!

**Comment by stefan2200** [comment]
I actually had to find it out myself since that feature wasn't implemented by me :)
The format is actually `%d.%m.%y %H:%M:%S"` and it takes two keys, start and end. So using this should work I think:
`"forced_peace_times": [{"start": "24.12.24 10:00:00", "end": "26.12.24 17:00:00"}]`

Regarding the issue with the web interface that is a known bug. I think it has something to do with how flask stores the bot's process handle in memory or something.

**Comment by MariusDac** [comment]
Thank you very much for your answer.I did try your suggestion for peace time and its working in the above format.
As for the web interface part,will try to sort it myself,you gave me a starting point!
Thank you for your help!Happy new year !
